#:kivy 2.0.0

<InputButton>:
    send_data: ""
    keycode: 0
    font_size: 80

<NumberButton@InputButton>:
    on_press: app.number_button_on_press(send_data=self.send_data)

<DecimalButton@InputButton>:
    on_press: app.decimal_button_on_press(send_data=self.send_data)

<OperatorButton@InputButton>:
    on_press: app.operator_button_on_press(send_data=self.send_data)

<EqualButton@InputButton>:
    on_press: app.equal_button_on_press(send_data=self.send_data)

<ACButton@InputButton>:
    on_press: app.ac_button_on_press(send_data=self.send_data)

<InputPanel>:
    rows: 5
    cols: 4

    ACButton:
        send_data: root.AC
        keycode: root.key_codes["escape"]
        text: "AC"
    Widget:
    Widget:
    OperatorButton:
        send_data: root.DIVI
        keycode: root.key_codes["/"]
        text: "÷"
    NumberButton:
        send_data: root.SEVEN
        keycode: root.key_codes["7"]
        text: "7"
    NumberButton:
        send_data: root.EIGHT
        keycode: root.key_codes["8"]
        text: "8"
    NumberButton:
        send_data: root.NINE
        keycode: root.key_codes["9"]
        text: "9"
    OperatorButton:
        send_data: root.MULTI
        keycode: root.key_codes["*"]
        text: "×"
    NumberButton:
        send_data: root.FOUR
        keycode: root.key_codes["4"]
        text: "4"
    NumberButton:
        send_data: root.FIVE
        keycode: root.key_codes["5"]
        text: "5"
    NumberButton:
        send_data: root.SIX
        keycode: root.key_codes["6"]
        text: "6"
    OperatorButton:
        send_data: root.MINUS
        keycode: root.key_codes["-"]
        text: "-"
    NumberButton:
        send_data: root.ONE
        keycode: root.key_codes["1"]
        text: "1"
    NumberButton:
        send_data: root.TWO
        keycode: root.key_codes["2"]
        text: "2"
    NumberButton:
        send_data: root.THREE
        keycode: root.key_codes["3"]
        text: "3"
    OperatorButton:
        send_data: root.PLUS
        keycode: root.key_codes["+"]
        text: "+"
    Widget:
    NumberButton:
        send_data: root.ZERO
        keycode: root.key_codes["0"]
        text: "0"
    DecimalButton:
        send_data: root.DECIMAL
        keycode: root.key_codes["."]
        text: "."
    EqualButton:
        send_data: root.EQUAL
        keycode: root.key_codes["enter"]
        text: "="