#:kivy 2.0.0
<InputButton@Button>:
    font_size: 100

<InputPanel>:
    rows: 5
    cols: 4

    InputButton:
        id: ac
        text: "AC"
    Widget:
    Widget:
    InputButton:
        id: divi
        text: "÷"
    InputButton:
        id: seven
        text: "7"
    InputButton:
        id: eight
        text: "8"
    InputButton:
        id: nine
        text: "9"
    InputButton:
        id: multi
        text: "×"
    InputButton:
        id: four
        text: "4"
    InputButton:
        id: five
        text: "5"
    InputButton:
        id: six
        text: "6"
    InputButton:
        id: minus
        text: "-"
    InputButton:
        id: one
        text: "1"
    InputButton:
        id: two
        text: "2"
    InputButton:
        id: three
        text: "3"
    InputButton:
        id: plus
        text: "+"
    Widget:
    InputButton:
        id: zero
        text: "0"
    InputButton:
        id: decimal
        text: "."
    InputButton:
        id: equal
        text: "="