class SendCharacters:
    """
    ユーザーがボタンを押下したときにイベントハンドラに引数として送信される文字列
    """
    AC = "$"
    DIVI = "/"
    MULTI = "*"
    PLUS = "+"
    MINUS = "-"
    ONE = "1"
    TWO = "2"
    THREE = "3"
    FOUR = "4"
    FIVE = "5"
    SIX = "6"
    SEVEN = "7"
    EIGHT = "8"
    NINE = "9"
    ZERO = "0"
    DECIMAL = "."
    EQUAL = "="